import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from './../node_modules/vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
  initial: 'en',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('ru').create({
      langName: 'Русский',
      empty: "",
      title: 'Калькулятор пола ребенка',
      aboutPart1:'Здесь вы можете узнать пол будущего ребенка.  Для расчетов используется теория обновления крови, китайский лунный календарь  и японский календарь беременности.',
      aboutPart2:'Зная предполагаемую дату зачатия, вы можете узнать кого вы, вероятнее всего ждете - мальчика или девочку.  Также вы можете построить календарь,  в котором будут указан наиболее вероятный пол ребенка для каждого дня зачатия. Эта функция будет полезна тем, кто планирует беременность.',
      aboutPart3:'Для расчетов используется теория обновления крови, китайский лунный календарь  и традиционный японский метод. Вы можете использовать в расчетах все три метода сразу или выбрать предпочтительные.',
      modeSectionHeader: 'Выберите режим',
      mbdayTitle: 'Дата рождения матери',
      fbdayTitle: 'Дата рождения отца',
      concdayTitle: 'Дата зачатия',
      datemodeTitle: 'Спрогнозировать пол ребенка по дате зачатия',
      calendarmodeTitle: 'Построить календарь зачатия',
      methodslistTitle: 'Методы расчета',
      bloodMethodName: 'Старшинства крови',
      chineseMethodName: 'Китайский лунный календарь',
      japaneseMethodName: 'Японский календарь беременности',
      bloodMethodFullName: 'Рассчитано по методу старшинства крови',
      chineseMethodFullName: 'Рассчитано по китайскому лунному календарю',
      japaneseMethodFullName: 'Рассчитано по японскому календарю беременности',
      displayOverallTitle: 'Показывать обобщенный прогноз',
      displaySeparatedTitle: 'Показывать результаты методов отдельно',
      methodsWarn: 'Выберите как минимум один метод',
      datesWarn: 'Чтобы получить прогноз, укажите даты рождения родителей',
      chineseAgeWarn: 'Расчет по китайскому лунному календарю доступен для возраста матери от 18 до 45 лет. Указанный вами возраст не входит в этот промежуток и прогноз по китайскому лунному календарю не рассчитан.',
      bloodMethodDescription: 'Метод, основанный на теории обновления крови. Мужская кровь обновляется раз в 4 года, женская - раз в три. Чья кровь моложе на момент зачатия, такого пола будет ребенок. Если один из родителей перенес крупную кровопотерю (роды, операция, переливание крови), для правильного расчета вместо даты рождения следует указать дату кровопотери.',
      chineseMethodDescription: 'Расчет по китайскому лунному календарю определяет пол будущего ребенка по возрасту матери и месяцу зачатия. Этот метод популярен в Китае среди тех, кто планирует беременность и хочет ребенка определенного пола.',
      japaneseMethodDescription: 'Японская система прогнозирования, которая рассчитывает вероятность появления мальчика или девочки, основываясь на возрасте отца и матери, а также месяце зачатия. Для каждой комбинации метод рассчитывает вероятность появления мальчика или девочки. Этот метод популярен в Японии.',
      readMore:"Подробнее",
      confidenceBlood: "Уверенность в прогнозе рассчитывается на основании разницы возрастов крови отца и матери. Чем больше разница возрастов, тем выше уверенность в прогнозе",
      confidenceChinese: 'Этот метод не рассчитывает уверенность в прогнозе',
      confidenceJapanese: 'Уверенность в прогнозе вычисляется на основании данных таблицы.',
      chineseAgeCalendarError: 'Для некоторых дат не удалось рассчитать прогноз по китайскому лунному календарю, так как лунный возраст матери в эти даты не входит в диапазон от 18 до 45 лет',
      boy: 'Мальчик',
      girl: 'Девочка',
      motherBDayError:'Дата рождения матери позже даты зачатия. Введите верные даты для расчета.',
      fatherBDayError: 'Дата рождения отца позже даты зачатия. Введите верные даты для расчета.',
      motherBDayCalendarError:'Для некоторых дат рассчитать прогноз невозможно, так как расчетная дата раньше указанной даты рождения матери',
      fatherBDayCalendarError: 'Для некоторых дат рассчитать прогноз невозможно, так как расчетная дата раньше указанной даты рождения отца',
      boyorgirl: 'Мальчик или девочка с равной вероятностью',
      gender: 'Пол',
      precision: 'Уверенность в прогнозе',
      calendarHeader: 'Календарь вероятности зачатия мальчика или девочки',
      methodsListPanelTitle:"Использовать в расчете методы",
      calendarFooter: 'Условные обозначения',
      powerindex: 'Метод обновления крови и японский метод позволяют рассчитать уверенность в прогнозе.',
      shareUs: "Рекомендуйте BabyCalc друзьям",
      writeDevsTitle: "Написать разработчикам",
      writeDevsText1: "Есть вопросы?",
      writeDevsText2: "Напишите нам на электронную почту!",
      donateDevsTitle: "Поддержать разработчиков",
      donateDevsText1: "Если вам нравится BabyCalc, вы можете  материально поддержать разработчиков переводом PayPal",
      donateDevsText2: "Спасибо!",
      donateDevsText3: "Поддержите разработчиков материально",
      disclaimer: 'Внимание! Калькулятор основан на методах расчета, не подтвержденных официальными медицинскими исследованиями и не гарантирует 100% точности!',
      developersAndDonate: "Связь с разработчиками и Donate",
      mailButton:'Отправить Email',
      donateButton: 'Отправить перевод PayPal',
      ContentH2: "Методы предсказания пола будущего ребенка",
      ContentP1_1:"Современная медицина позволяет с высокой точностью определить пол ребенка уже через несколько недель после зачатия. Однако вопрос о том, какого пола будущий малыш, интересовал мам задолго до появления УЗИ и анализов крови. Так появились ",
      ContentP1_2:"различные методики предсказания пола ребенка",
      ContentP1_3:" - основанные на астрологии, многовековых наблюдениях и подмеченных закономерностях. Конечно, ни один из подобных методов не гарантирует 100%  точности, тем не менее большинство мам отмечает верность традиционных методик прогнозирования.",
      ContentP2:"На этой странице вы можете рассчитать пол будущего ребенка по 3 наиболее популярным традиционным методам:",
      ContentP3:"Все, что требуется сделать - ввести даты рождения родителей. Если вы знаете дату зачатия, вы можете спрогнозировать пол ребенка по трем методам сразу. Если же вы только планируете беременность, выберите режим «построить календарь прогнозов». Приложение покажет наиболее вероятный пол ребенка на каждый день зачатия. ",
      ContentP4:"Календарный прогноз можно рассчитать с использованием любых из предложенных методов. Вы можете выбрать все три, или отметить только некоторые. Календарный прогноз можно посмотреть в упрощенном виде, или отобразить данные по каждому методу  отдельно.",
      ContentP5:"Для методов «обновление крови» и «японская таблица» в прогнозе указывается уверенность. Чем больше уверенность, тем вероятнее появление ребенка указанного пола.",
      ContentP6:"Так как методики прогнозирования пола не основываются на точных медицинских исследованиях и создавались независимо друг от друга, в некоторых случаях результаты их расчета не совпадают.",
      ContentP7:"Одна из самых простых методик прогнозирования пола будущего ребенка - по «возрасту» крови.  Предполагается, что у мужчин полное обновление состава крови происходит раз в 4 года. А у женщин - раз в 3 года. Чтобы узнать «возраст крови», необходимо разделить возраст отца на 4, а возраст матери - на 3. Отбросив целую часть, получаем «возраст крови» каждого из родителей. Другими словами, количество полных циклов обновления не принимается во внимание. Если кровь матери «моложе», то есть обновилась позже, чем кровь отца - будет девочка. Если же «моложе» кровь отца - родится мальчик.",
      ContentP8:"Крупные потери крови могут сдвинуть естественный цикл обновления крови. Если один из родителей перенес операцию, донорство или переливание крови, то вместо даты рождения следует указать дату последней потери крови. Это будет началом отсчета цикла обновления крови.",
      ContentP9:"Анализ отзывов на эту методику на  форумах для беременных показывает, что точность подобного прогноза приблизительно равна 62%.",
      ContentP10:"Эта методика прогнозирования пола особенно популярна среди будущих мам в России, Украине и Беларуси.",
      ContentP11:"В Китае широкое распространение получил метод прогнозирования пола будущего ребенка по лунному календарю. Этот метод основан на древней таблице, составленной более 1000 лет назад.  Таблица рассчитана для возраста матери от 18 до 45 лет. В ней для каждого возраста и месяца, в котором произошло зачатие, указан пол будущего ребенка. Возраст отца не используется для расчета.",
      ContentP12:"Данную таблиц несложно найти в интернете. Однако следует учитывать, что для правильного расчета требуется указать возраст и месяц зачатия по китайскому лунному календарю. Возраст и дата зачатия по лунному календарю и по европейскому не совпадают. Это обусловлено тем, что по лунному календарю возраст на момент рождения уже составляет 1 год, и прибавляется не в день рождения, а в национальный праздник Весны или Китайский новый год.",
      ContentP13:"BabyCalc автоматически переведет указанные вами даты в лунный календарь и выполнит верный расчет.",
      ContentP14:"Этот метод используется многими китайскими семьями, которые хотят ребенка определенного пола.",
      ContentP15:"Японский метод прогнозирования пола ребенка схож с китайским, но он также учитывает дату рождения отца. Он включает 2 таблицы. В первой таблице для каждой пары «месяц рождения отца - месяц рождения матери» содержится число. Во второй таблице для каждого числа из первой таблицы и календарного месяца указана вероятность зачатия мальчика или девочки. Таким образом, японский метод позволяет «спланировать» пол будущего ребенка на любой период времени.",
      ContentP16:"Найти японские таблицы зачатия в интернете не составляет труда. Чтобы воспользоваться ими, не нужно переводить даты в лунный календарь. ",
      ContentP17:"Результаты опросов показывают, что точность японского метода составляет 70-80%.",
      ContentP18:"Запланировать пол ребенка невозможно - так утверждает официальная медицина. Тем не  многие пары отмечают, что успешно использовали различные «народные» методики, чтобы зачать дочь или сына. Так, в Китае многие пары планируют дату зачатия по лунному календарю, а в России пытаются спрогнозировать, рассчитывая «возраст» крови родителей.",
      ContentP19:"Если вы планируете ребенка, при помощи BabyCalc вы можете построить календарь, в котором будут отмечены даты, в которые наиболее вероятно зачать девочку или мальчика. Чтобы построить прогноз, выберите режим «Построить календарь прогнозов», введите даты рождения родителей. Вы можете выбрать один или несколько методов для расчета прогноза, отмечая нужные методики слева от календаря.",
      ContentP20:"Однако, не стоит относиться к подобному планированию слишком серьезно - ни один из используемых в BabyCalc методов не подтвержден научными исследованиями. Воспринимайте прогноз исключительно как развлекательную информацию.",
      ContentL1:"обновление крови,",
      ContentL2:"китайский лунный календарь,",
      ContentL3:"японский календарь зачатия",
      ContentH3_1: "Как работает предсказание пола ребенка?",
      ContentH3_2: "Почему прогнозы по разным методам не совпадают?",
      ContentH3_3: "Какие методы расчета использует этот сайт?",
      ContentH4_1: "Метод обновления крови",
      ContentH4_2: "Китайский лунный календарь",
      ContentH4_3: "Японская таблица",
      ContentH3_4: "Как запланировать пол ребенка?",
      menu: "Меню",
      menuMain: "Калькулятор пола ребенка",
      menuAbout: "Как работает BabyCalc",
      menuMethods: "Методы прогнозирования пола",
      menuBlood:"Пол ребенка по крови",
      menuChina:"Китайский календарь зачатия",
      menuJapan:"Японский календарь зачатия",
      menuSell: "Встраиваемый BabyCalc для вашего сайта",
      chinese1: "Китайский календарь зачатия",
      chinese2: "Китайская таблица определения пола  ребенка по возрасту матери известна более 700 лет. Ее оригинал сохранился и по сей день хранится в Пекинском Институте. Заслуживший признание в Китае,  календарь пола ребенка сегодня популярен во всем мире. Его используют как для того, чтобы узнать пол ребенка по таблице, так и для того, чтобы выбрать наиболее удачный день, чтобы зачать мальчика или девочку.",
      chinese3: "Несмотря на то, что китайская таблица пола ребенка не основывается на медицинских или научных теориях, более 75% мам отмечают ее достоверность.",
      chinese4: "Как определить пол ребенка по дате зачатия?",
      chinese5: "Чтобы узнать пол ребенка по таблице, необходимо сперва рассчитать лунный возраст матери. Дело в том,  что китайский календарь определения пола ребенка построен на основе китайского лунного календаря. Согласно ему, возраст матери будет на год или два больше возраста по европейскому календарю. ",
      chinese6: "Вы можете узнать свой лунный возраст онлайн, воспользовавшись калькулятором на этой странице.",
      chinese7: "Далее необходимо узнать месяц зачатия по лунному календарю. Для этого введите предполагаемую дату зачатия в поле ниже.",
      chinese8: "Зная свой лунный возраст и месяц зачатия, остается лишь найти в таблице соответствующую ячейку, в ней будет указан наиболее вероятный пол будущего ребенка. ",
      chinese9: "Гораздо проще рассчитать пол ребенка онлайн, используя китайский календарь беременности - на главной странице этого сайта.",
      chinese10: "Китайский календарь зачатия",
      chinese11: "Если вы хотите зачать ребенка определенного пола, воспользуйтесь функцией «Календарь зачатия» на главной странице этого сайта. Калькулятор рассчитает наиболее благоприятные интервалы для зачатия мальчика или девочки не только на 2020 год, но и на любой нужный вам интервал.",
      chinese12: "В календаре будут отражены периоды, в которые наиболее вероятно зачатие мальчика или девочки.",
      chinese13: "Не забывайте, что определение пола по китайскому календарю не обладает 100% точностью и может использоваться исключительно в развлекательных целях.",
      lunarSolar1:"Узнать лунный возраст",
      lunarSolar2:"Введите вашу дату рождения",
      lunarSolar3:"Ваш лунный возраст",
      lunarSolar4:"Введите дату зачатия",
      lunarSolar5:"Лунный месяц зачатия",
      lunarSolar6:"Рассчитать лунный месяц зачатия",
      chinaTable1:"Китайская таблица расчета пола ребенка",
      chinaTable2:"Лунный возраст матери",
      chinaTable3:"Лунный месяц зачатия",
      blood1:"Пол ребенка по обновлению крови",
      blood2:"Определение пола ребенка по крови основано на предположении, что кровь, слизистые оболочки и другие ткани человека полностью обновляются в процессе жизни с определенной периодичностью. Для мужчин период полного обновления крови и тканей длится 4 года, а для женщин - 3 года. Если на момент зачатия кровь женщины будет «моложе» крови мужчины, родится девочка. Если же кровь мужчины обновилась недавно, а женщины - давно, то родится мальчик. Другими словами, ребенок будет иметь пол того родителя, чья кровь «моложе».",
      blood3:"При определении пола ребенка по крови следует учитывать, что если один или оба родителя перенесли крупные кровопотери в прошлом, вместо даты рождения при расчетах нужно использовать дату потери крови. Примеры ситуаций, когда происходит крупная потеря крови - серьезные травмы, переливание крови, донорство крови, роды, серьезные операции.",
      blood4:"Как рассчитать пол ребенка по обновлению крови?",
      blood5_1:"Разделить возраст отца на 4, а возраст матери - на 3.",
      blood5_2:"У полученных чисел отбросить целые части (количество полных циклов не влияет на «возраст» крови) и сравнить остатки.",
      blood5_3:"У кого остаток меньше, тот и обладает более «молодой» кровью, следовательно такого пола и будет ребенок.",
      blood6:"Чтобы не заниматься расчетами вручную - используйте калькулятор обновления крови на главной странице BabyCalc. Достаточно ввести даты рождения родителей и предполагаемую дату зачатия, и калькулятор рассчитает пол ребенка онлайн.",
      blood7:"В отличие от множества других калькуляторов пола по крови,  BabyCalc позволяет рассчитать уверенность в прогнозе пола ребенка. Уверенность в прогнозе рассчитывается на основании разницы «возрастов» крови. Так, если разница невелика, расчет может быть неверным, так как индивидуальные особенности организма могут замедлить или ускорить процесс обновления крови.",
      blood8:"Зачатие по обновлению крови",
      blood9:"Определение пола по крови нередко используется для планирования зачатия малыша. Например, если пара мечтает о мальчике, зачатие ребенка можно запланировать на период, когда кровь мужчины будет  «моложе».",
      blood10:"Если вы хотите узнать наиболее благоприятные периоды для зачатия девочки или мальчика, постройте индивидуальный календарь зачатия на главной странице этого сайта. Программа автоматически рассчитает периоды наиболее вероятного зачатия мальчика или девочки на 2020 или любой другой год.",
      blood11:"Внимание! Определение пола ребенка по крови не основано на официальных медицинских исследованиях и не обладает 100% точностью. Все прогнозы представляются исключительно с развлекательной целью и не могут служить основой для принятия серьезных решений.",
      japTableHeader1:"Японская таблица зачатия, часть 1",
      japTableHeader2:"Японская таблица зачатия, часть 2",
      japTable1:"Месяц рождения мужчины",
      japTable2:"Месяц рождения женщины",
      japTable3:"Число из первой таблицы",
      japTable4:"Месяц зачатия",
      japanese1:"Это один из самых популярных и простых методов узнать, кого ожидает будущая мама -мальчика или девочку. Для того, чтобы узнать пол ребенка, потребуются лишь даты рождения родителей.",
      japanese2:"Как определить пол по японской таблице?",
      japanese3:"Японская таблица определения пола ребенка состоит из двух частей. В первой содержатся вспомогательные числа, во второй - вероятности рождения мальчика или девочки.",
      japanese4:"Чтобы определить пол ребёнка по японскому календарю, нужно:",
      japanese4_1:"В первой таблице найти столбец с месяцем рождения матери и строку с месяцем рождения отца",
      japanese4_2:"Запомнить число на пересечении столбца и строки",
      japanese4_3:"Во второй таблице найти строку с числом из первой таблицы и столбец с месяцем зачатия ребенка. На их пересечении указан пол будущего малыша и указана вероятность правильности прогноза. В некоторых ячейках указаны оба пола, это значит, что зачатие как мальчика, так и девочки, равновероятно.",
      japanese5:"Планирование пола ребенка по японской таблице",
      japanese6:"Если внимательно посмотреть на таблицу, можно увидеть, что некоторые месяцы отмечены высокой вероятностью рождения мальчика или девочки, другие же имеют примерно равное соотношение шансов. Если пара мечтает о ребенке определенного пола, следует выбирать для зачатия ребенка месяцы с наибольшей разницей вероятностей. Например, для пары, которой в первой таблице соответствует число 7, наибольшие шансы зачать мальчика во 2 и 10 месяц года, а девочку - в 3 и в 11.",
      japanese7:"Японский календарь беременности на 2020 год",
      japanese8:"При помощи BabyCalc вы можете бесплатно построить индивидуальный календарь зачатия по японской таблице. На главной странице введите даты рождения родителей и выберите режим «Календарь зачатия». Программа автоматически рассчитает наиболее благоприятные периоды для зачатия мальчика или девочки по японскому календарю, а также по китайскому лунному календарю и методу обновления крови. Вы можете построить прогноз на любой срок. ",
      japanese9:"Точность японского календаря беременности",
      japanese10:"Японская таблица определения пола давно стала популярной во многих странах мира. В странах Азии ее считают наиболее точным способом спрогнозировать пол будущего ребенка.",
      japanese11:"Отзывы о японской таблице беременности с форумов и из групп в социальных сетях говорят о том, что около 80% прогнозов верны.",
      japanese12:"На чем основано определение пола по японской таблице?",
      japanese13:"Пол ребенка зависит от набора хромосом, которые содержит сперматозоид. У женщин яйцеклетка имеет всегда одинаковый набор хромосом, а вот мужские клетки могут нести как мужскую комбинацию хромосом, так и женскую. Это - доказанный научный факт.",
      japanese14:"Современная медицина утверждает, что предсказать заранее, какой набор хромосом будет нести в себе сперматозоид, оплодотворивший яйцеклетку, невозможно.  Противоположное мнение высказала группа японских ученых. Они считают, что в одни временные циклы наиболее активны мужские клетки с мужским набором хромосом, в другие же - с женским.  Это предположение и послужило основой для составления японского календаря беременности.",
      japanese15:"Внимание! Метод определения пола ребенка по японской таблице не обладает 100% достоверностью и не подтвержден официальными медицинскими исследованиями.",
      japanese16:"Все прогнозы на сайте BabyCalc предоставляются исключительно в развлекательных целях и не могут служить основой для принятия серьезных решений.",
      p404_title:"Страница не найдена",
      p404_subtitle:"Страница, которую вы ищете, больше не существует",
      goToCalc:"Перейти в калькулятор пола ребенка и календарь беременности"

    }),

    new MLanguage('en').create({
      langName: 'English',
      empty: "",
      title: 'Baby gender calculator',
      aboutPart1:'Here you can find out the gender of the child. For calculations, the theory of blood renewal, the Chinese lunar calendar and the Japanese pregnancy calendar are used.',
      aboutPart2:'Knowing the estimated date of conception, you can find out who you are most likely waiting for - a boy or a girl. You can also build a calendar that will indicate the most likely gender of the child for each day of conception. This feature will be useful for those planning a pregnancy.',
      aboutPart3:'For calculations, the theory of blood renewal, the Chinese lunar calendar and the traditional Japanese method are used. You can use all three methods in the calculations at once or choose preferred ones.',
      modeSectionHeader: 'Choose mode',
      mbdayTitle: 'Mother\'s date of birth',
      fbdayTitle: ' Father\'s date of birth',
      concdayTitle: 'Conception date',
      datemodeTitle: 'Predict the gender of the baby by the date of conception',
      calendarmodeTitle: 'Pregnacy conception calculator',
      methodslistTitle: 'Calculation methods',
      bloodMethodName: 'Blood seniority',
      chineseMethodName: 'Chinese moon calendar',
      japaneseMethodName: 'Japanese pregnacy calendar',
      bloodMethodFullName: 'Calculated by the method of blood seniority',
      chineseMethodFullName: 'Calculated by the Chinese lunar calendar',
      japaneseMethodFullName: 'Calculated by the Japanese pregnacy calendar',
      displayOverallTitle: 'Show generalized forecast',
      displaySeparatedTitle: 'Show method results separately',
      methodsWarn: 'Please select at least one method',
      datesWarn: 'To get a forecast, enter the date of birth of parents',
      chineseAgeWarn: 'Calculation according to the Chinese lunar calendar is available for mother\'s age from 18 to 45 years. The age you specified is not included in this period and the forecast for the Chinese lunar calendar is not calculated.',
      bloodMethodDescription: 'A method based on the theory of blood renewal. Male blood is renewed every 4 years, female blood - every three years. Whose blood is younger at the time of conception, this gender will be a child. If one of the parents suffered a major blood loss (childbirth, surgery, blood transfusion), for the correct calculation, the date of blood loss should be entered instead of the date of birth.',
      chineseMethodDescription: 'The calculation according to the Chinese lunar calendar determines the gender of the unborn child according to the age of the mother and the month of conception. This method is popular in China among those who are planning a pregnancy and want a baby of a certain gender.',
      japaneseMethodDescription: 'A Japanese forecasting system that calculates the probability of a boy or girl based on the age of the father and mother, as well as the month of conception. For each combination, the method calculates the probability of a boy or girl. This method is popular in Japan.',
      confidenceBlood: "Confidence in the forecast is calculated based on the difference between the age of blood of mother and father. The greater the age difference, the higher the confidence in the forecast.",
      confidenceChinese: 'This method does not calculate confidence in the forecast.',
      confidenceJapanese: "Confidence in the forecast is calculated based on the data in the table.",
      chineseAgeCalendarError: 'For some dates, it was not possible to calculate the forecast for the Chinese lunar calendar, since the lunar age of the mother on these dates is not in the range from 18 to 45 years',
      motherBDayError:'Mother\'s date of birth later than conception date. Enter the correct date for the calculation.',
      fatherBDayError: 'Father\'s date of birth later than conception date. Enter the correct date for the calculation.',
      motherBDayCalendarError:'For some dates to calculate the forecast is not possible, since the estimated date before that date the birth mother',
      fatherBDayCalendarError: 'For some dates to calculate the forecast is not possible, since the estimated date before that date the birth father',
      boy: 'Boy',
      girl: 'Girl',
      boyorgirl: 'Boy or girl with equal probability',
      gender: 'Gender',
      calendarHeader: 'Calendar probability of conceiving a boy or girl',
      methodsListPanelTitle:"Use methods in the calculation",
      calendarFooter: 'Legend',
      precision: 'Confidence',
      powerindex: 'The blood seniority method and the Japanese method make it possible to calculate confidence in the prognosis.',
      shareUs: "Recommend BabyCalc to friends",
      writeDevsTitle: "Write to developers",
      writeDevsText1: "Have questions?",
      writeDevsText2:"Email us!",
      donateDevsTitle: "Donate",
      donateDevsText1: "If you like BabyCalc, you can financially support the developers PayPal transfer",
      donateDevsText2: "Thank you so much!",
      donateDevsText3: "Support developers financially",
      disclaimer: 'Attention! The calculator is based on calculation methods not confirmed by official medical research and does not guarantee 100% accuracy!',
      developersAndDonate: "Contact developers and Donate",
      mailButton:'Send Email',
      donateButton: 'Send PayPal transfer',
      ContentH2: "Methods of predicting the gender of the child",
      ContentP1_1:"Modern medicine allows you to accurately determine the gender of the child within a few weeks after conception. However, the question of what gender the future baby was interested in by mothers long before the appearance of ultrasound and blood tests. So there were",
      ContentP1_2:"various methods for predicting the gender of the child ",
      ContentP1_3:"- based on astrology, centuries-old observations and observable patterns. Of course, none of these methods guarantees 100% accuracy, however, most mothers note the fidelity of traditional forecasting techniques.",
      ContentP2:"On this page, you can calculate the gender of the child using the 3 most popular traditional methods:",
      ContentP3:"All you need to do is enter your parents ’birth dates. If you know the date of conception, you can predict the gender of the child in three ways at once. If you are just planning a pregnancy, select the \"build a forecast calendar\" mode. The application will show the most likely gender of the child for each day of conception.",
      ContentP4:"The calendar forecast can be calculated using any of the proposed methods. You can select all three, or mark only a few. The calendar forecast can be viewed in a simplified form, or display data for each method separately.",
      ContentP5:"For the methods \"blood renewal\" and \"Japanese table\", the forecast indicates confidence. The more confidence, the more likely the appearance of a child of the specified gender.",
      ContentP6:"Since the methods for predicting gender are not based on accurate medical research and were created independently of each other, in some cases the results of their calculation do not match.",
      ContentP7:"One of the simplest methods for predicting the gender of a child is by the \"age\" of blood. It is assumed that in men, a complete renewal of the blood composition occurs every 4 years. And for women - every 3 years. To find out the \"age of blood\", it is necessary to divide the age of the father by 4, and the age of the mother by 3. Discarding the integer part, we obtain the \"age of blood\" of each of the parents. In other words, the number of full update cycles is not taken into account. If the mother’s blood is \"younger\", that is, updated later than her father’s blood, there will be a girl. If the father’s blood is \"younger\", a boy will be born.",
      ContentP8:"Large blood loss can shift the natural cycle of blood renewal. If one of the parents has undergone surgery, donation or blood transfusion, then instead of the date of birth, the date of the last blood loss should be indicated. This will be the start of the blood renewal cycle.",
      ContentP9:"Analysis of reviews of this methodology on forums for pregnant women shows that the accuracy of such a forecast is approximately 62%.",
      ContentP10:"This gender prediction technique is especially popular among expectant mothers in Russia, Ukraine and Belarus.",
      ContentP11:"In China, the lunar calendar method for predicting the gender of the child has become widespread. This method is based on an ancient table compiled more than 1000 years ago. The table is calculated for mother's age from 18 to 45 years. In it, for each age and month in which the conception occurred, the the gender of the child is indicated. Father's age is not used for calculation.",
      ContentP12:"This table is easy to find on the Internet. However, it should be borne in mind that for the correct calculation, you must specify the age and month of conception according to the Chinese lunar calendar. The age and date of conception on the lunar calendar and the European do not match. This is due to the fact that according to the lunar calendar, the age at the time of birth is already 1 year, and is added not on the day of birth, but on the national holiday of Spring or Chinese New Year.",
      ContentP13:"BabyCalc will automatically translate your dates into the lunar calendar and perform the correct calculation.",
      ContentP14:"This method is used by many Chinese families who want a child of a certain gender.",
      ContentP15:"The Japanese method for predicting the gender of the child is similar to the Chinese, but it also takes into account the date of birth of the father. It includes 2 tables. In the first table for each pair, \"father’s month of birth - mother’s month of birth\" contains a number. In the second table, for each number from the first table and the calendar month, the probability of conceiving a boy or girl is indicated. Thus, the Japanese method allows you to plan the gender of the child for any period of time.",
      ContentP16:"Finding Japanese baby charts on the Internet is easy. To use them, you do not need to translate dates into the lunar calendar.",
      ContentP17:"Surveys show that the accuracy of the Japanese method is 70-80%.",
      ContentP18:"It is impossible to plan the sex of the child - as official medicine claims. However, not many couples note that they have successfully used various \"folk\" techniques to conceive a daughter or son. So, in China, many couples plan the date of conception according to the lunar calendar, and in Russia they try to predict, calculating the \"age\" of the blood of the parents.",
      ContentP19:"If you are planning a baby, with the help of BabyCalc you can build a calendar, which will mark the dates on which it is most likely to conceive a girl or boy. To build a forecast, select the \"Build Forecast Calendar\" mode, enter the dates of birth of the parents. You can select one or several methods for calculating the forecast, marking the necessary methods to the left of the calendar.",
      ContentP20:"However, do not take such planning too seriously - not one of the methods used in BabyCalc has been confirmed by scientific research. Think of the forecast as entertaining information only.",
      ContentL1:"blood renewal,",
      ContentL2:"chinese baby chart,",
      ContentL3:"japanese baby chart",
      ContentH3_1: "How does gender prediction work?",
      ContentH3_2: "Why are the forecasts for different methods do not match?",
      ContentH3_3: "What calculation methods does this site use?",
      ContentH4_1: "Blood renewal method",
      ContentH4_2: "Chinese lunar calendar",
      ContentH4_3: "Japanese table",
      ContentH3_4: "How to plan the gender of the child?",
      menu: "Menu",
      menuMain: "Baby gender calculator",
      menuAbout: "How BabyCalc works",
      menuMethods: "Gender prediction methods",
      menuBlood:"Gender of a child for blood renewal",
      menuChina:"Chinese baby chart",
      menuJapan:"Japanese baby chart",
      menuSell: "Embedded BabyCalc for your website",
      chinese1: "Chinese baby chart",
      chinese2: "The Chinese table for determining the sex of the child by the age of the mother is known for more than 700 years. Its original has been preserved and is still stored at the Beijing Institute. Recognized in China, the baby gender calendar is now popular all over the world. It is used both to find out the sex of the child from the table, and in order to choose the most successful day to conceive a boy or girl.",
      chinese3: "Despite the fact that the Chinese table of the sex of the child is not based on medical or scientific theories, more than 75% of mothers note its reliability.",
      chinese4: "How to determine the sex of the child by the date of conception?",
      chinese5: "To find out the sex of the child from the table, you must first calculate the lunar age of the mother. The fact is that the Chinese calendar for determining the sex of the child is built on the basis of the Chinese lunar calendar. According to him, the mother’s age will be a year or two more than the age according to the European calendar.",
      chinese6: "You can find out your lunar age online using the calculator on this page.",
      chinese7: "Next, you need to find out the month of conception on the lunar calendar. To do this, enter the estimated date of conception in the field below.",
      chinese8: "Knowing your lunar age and month of conception, it remains only to find the appropriate cell in the table, it will indicate the most likely gender of the child.",
      chinese9: "It is much easier to calculate the sex of the baby online using the Chinese pregnancy calendar - on the main page of this site.",
      chinese10: "Chinese conception calendar",
      chinese11: "If you want to conceive a child of a certain gender, use the function \"Conception Calendar\" on the main page of this site. The calculator will calculate the most favorable intervals for the conception of a boy or girl, not only for 2020, but also for any interval you need.",
      chinese12: "The calendar will show the periods in which the conception of a boy or girl is most likely.",
      chinese13: "Do not forget that gender determination on the Chinese calendar does not have 100% accuracy and can be used exclusively for entertainment purposes.",
      lunarSolar1:"How to find out your lunar age?",
      lunarSolar2:"Enter your date of birth",
      lunarSolar3:"Your lunar age",
      lunarSolar4:"Enter date of conception",
      lunarSolar5:"Lunar month of conception",
      lunarSolar6:"Calculate the lunar month of conception",
      chinaTable1:"Chinese baby chart",
      chinaTable2:"Lunar age of mother",
      chinaTable3:"Lunar month of conception",
      blood1:"Gender of a child for blood renewal",
      blood2:"The determination of a child’s gender by blood is based on the assumption that the blood, mucous membranes and other tissues of a person are completely updated in the process of life with a certain frequency. For men, the period of complete renewal of blood and tissues lasts 4 years, and for women - 3 years. If at the time of conception the blood of a woman is \"younger\" than the blood of a man, a girl will be born. If the blood of a man has been updated recently, and women - a long time ago, then a boy will be born. In other words, the child will have the gender of the parent whose blood is \"younger\".",
      blood3:"When determining the sex of the child by blood, it should be borne in mind that if one or both parents suffered major blood loss in the past, instead of the date of birth, the date of blood loss should be used in the calculations. Examples of situations when a major blood loss occurs - serious injuries, blood transfusion, blood donation, childbirth, serious surgery.",
      blood4:"How to calculate the sex of the child for blood renewal?",
      blood5_1:"Divide the father’s age by 4, and the mother’s age by 3.",
      blood5_2: "Discard the whole parts from the received numbers (the number of complete cycles does not affect the \"age\" of the blood) and compare the residues.",
      blood5_3:"Who has a smaller balance, he has a more \"young\" blood, therefore this gender will be a child.",
      blood6:"To avoid manual calculations, use the Blood Update Calculator on the BabyCalc home page. It is enough to enter the dates of birth of the parents and the estimated date of conception, and the calculator will calculate the gender of the child online.",
      blood7:"Unlike many other blood gender calculators, BabyCalc allows you to calculate confidence in the prognosis of the baby's gender. Confidence in the prognosis is calculated based on the difference in the \"ages\" of blood. So, if the difference is small, the calculation may be incorrect, as the individual characteristics of the body can slow down or accelerate the process of blood renewal.",
      blood8:"Conception by blood renewal",
      blood9:"The determination of gender by blood is often used to plan the conception of a baby. For example, if a couple dreams of a boy, the conception of a child can be planned for a period when the man’s blood will be \"younger\".",
      blood10:"If you want to find out the most favorable periods for the conception of a girl or boy, build an individual conception calendar on the main page of this site. The program will automatically calculate the periods of the most probable conception of a boy or girl for 2020 or any other year.",
      blood11:"Attention! Determining a child’s gender by blood is not based on official medical research and does not have 100% accuracy. All forecasts are presented for entertainment purposes only and cannot serve as the basis for serious decisions.",
      japTableHeader1:"Japanese baby chart, Part 1",
      japTableHeader2:"Japanese baby chart, Part 2",
      japTable1:"Man's month of birth",
      japTable2:"Woman's month of birth",
      japTable3:"The number from the first table",
      japTable4:"Conception month",
      japanese1:"This is one of the most popular and easiest methods to find out who the expectant mother is expecting - a boy or a girl. In order to find out the gender of the child, only the dates of birth of the parents will be required.",
      japanese2:"How to predict baby gender by japanese baby chart",
      japanese3:"Japanese baby chart is in two parts.  The first contains auxiliary numbers, the second contains the probabilities of the birth of a boy or girl.",
      japanese4:"To determine the gender of the child on the Japanese calendar, you need:",
      japanese4_1:"In the first table, find the column with the month of birth of the mother and the row with the month of birth of the father.",
      japanese4_2:"Remember the number at the intersection of the column and row",
      japanese4_3:"In the second table, find the row with the number from the first table and the column with the month of conception. At their intersection, the gender of the future baby is indicated and the probability of the correctness of the forecast is indicated. Both genders are indicated in some cells, which means that the conception of a boy and a girl is equally probable.",
      japanese5:"Japanese gender planning",
      japanese6:"If you look closely at the table, you can see that some months are marked by a high probability of giving birth to a boy or girl, while others have an approximately equal odds ratio. If a couple dreams of a child of a certain gender, you should choose the months with the greatest difference in probability for conceiving a child. For example, for a couple to whom the number 7 in the first table corresponds, the greatest chances to conceive a boy at 2 and 10 months of the year, and a girl at 3 and 11.",
      japanese7:"Japanese Pregnancy Calendar 2020",
      japanese8:"With BabyCalc, you can build an individual conception calendar for a Japanese table for free. On the main page, enter the birth dates of the parents and select the \"conception calendar\" mode. The program will automatically calculate the most favorable periods for the conception of a boy or girl according to the Japanese calendar, as well as the Chinese lunar calendar and the method of updating the blood. You can build a forecast for any period.",
      japanese9:"The accuracy of the Japanese baby chart",
      japanese10:"The Japanese baby chart has long been popular in many countries around the world. In Asia, she is considered the most accurate way to predict the gender of the child.",
      japanese11:"Reviews of the Japanese baby chart from forums and social media groups suggest that about 80% of forecasts are correct.",
      japanese12:"What is the basis for determining gender by a Japanese baby chart?",
      japanese13:"The gender of the child depends on the set of chromosomes that the sperm contains. In women, the egg always has the same set of chromosomes, but male cells can carry both the male combination of chromosomes and the female. This is a proven scientific fact.",
      japanese14:"Modern medicine claims that it is impossible to predict in advance which set of chromosomes the sperm that have fertilized the egg will carry. The opposite opinion was expressed by a group of Japanese scientists. They believe that in some time cycles, the most active are male cells with a male set of chromosomes, and in others, with a female one. This assumption served as the basis for the compilation of the Japanese pregnancy calendar.",
      japanese15:"Attention! The method for determining the baby gender according to the Japanese table does not have 100% certainty and is not confirmed by official medical research.",
      japanese16:"All forecasts on the BabyCalc website are provided for entertainment purposes only and cannot serve as the basis for serious decisions.",
      p404_title:"Page not found",
      p404_subtitle:"The page you are looking for no longer exists",
      goToCalc:"Go to the baby gender calculator and pregnancy calendar"

    }),
    new MLanguage('es').create({
      langName: 'Español',
      empty: "",
      title: 'Calculadora de género de bebé',
      aboutPart1:'Aquí puede averiguar el género del feto. Para los cálculos, se utilizan la teoría de la renovación de la sangre, el calendario lunar chino y el calendario de embarazo japonés.',
      aboutPart2:'Conociendo la fecha estimada de la concepción, puede averiguar a quién está esperando: un niño o una niña. También puede crear un calendario que indique el género más probable del niño para cada día de concepción. Esta característica será útil para quienes planean un embarazo.',
      aboutPart3:'Para los cálculos, se utilizan la teoría de la renovación de la sangre, el calendario lunar chino y el método tradicional japonés. Puede usar los tres métodos en los cálculos a la vez o elegir los preferidos.',
      modeSectionHeader: 'Elige un modo',
      mbdayTitle: 'Fecha de nacimiento de la madre',
      fbdayTitle: 'Fecha de nacimiento del padre',
      concdayTitle: 'Fecha de la concepción',
      datemodeTitle: 'Predecir el género del niño por la fecha de concepción',
      calendarmodeTitle: 'Calculadora de concepción del embarazo',
      methodslistTitle: 'Métodos de cálculo',
      bloodMethodName: 'Antigüedad de sangre',
      chineseMethodName: 'El calendario lunar chino',
      japaneseMethodName: 'El calendario de embarazo japonés',
      bloodMethodFullName: 'Calculado por el método de antigüedad de sangre',
      chineseMethodFullName: 'Calculado según el calendario lunar chino',
      japaneseMethodFullName: 'Calculado por el calendario de embarazo japonés',
      displayOverallTitle: 'Mostrar pronóstico generalizado',
      displaySeparatedTitle: 'Mostrar los resultados del método por separado',
      methodsWarn: 'Por favor seleccione al menos un método',
      chineseAgeWarn: 'El cálculo según el calendario lunar chino está disponible para la edad de la madre de 18 a 45 años. La edad que especificó no se incluye en este período y no se calcula el pronóstico para el calendario lunar chino.',
      datesWarn: 'Para obtener un pronóstico, especifique las fechas de nacimiento de los padres',
      bloodMethodDescription: 'El método se basa en la teoría de la renovación sanguínea. La sangre masculina se renueva cada 4 años, la sangre femenina, cada tres años. Cuya sangre es más joven al momento de la concepción, tal género tendrá un hijo',
      chineseMethodDescription: 'El cálculo según el calendario lunar chino determina el gender del feto según la edad de la madre y el mes de la concepción. Este método es popular en China entre quienes planean un embarazo y quieren un bebé de cierto género.',
      japaneseMethodDescription: 'Un sistema de pronóstico japonés que calcula la probabilidad de un niño o niña en función de la edad del padre y la madre, así como el mes de la concepción. Para cada combinación, el método calcula la probabilidad de un niño o niña. Este método es popular en Japón.',
      confidenceBlood: "La confianza en el pronóstico se calcula en función de la diferencia en las edades de la sangre del padre y la madre. Cuanto mayor es la diferencia de edad, mayor es la confianza en el pronóstico.",
      confidenceChinese: 'Este método no calcula la confianza en el pronóstico.',
      confidenceJapanese: "La confianza en el pronóstico se calcula con base en los datos de la tabla.",
      chineseAgeCalendarError: 'Para algunas fechas, no fue posible calcular el pronóstico para el calendario lunar chino, ya que la edad lunar de la madre en estas fechas no está en el rango de 18 a 45 años.',
      motherBDayError:'Fecha de nacimiento de la madre posterior a la fecha de concepción. Introduzca la fecha correcta para el cálculo.',
      fatherBDayError: 'Fecha de nacimiento del padre posterior a la fecha de concepción. Introduzca la fecha correcta para el cálculo.',
      motherBDayCalendarError:'Para algunas fechas para calcular el pronóstico no es posible, ya que la fecha estimada antes de esa fecha la madre',
      fatherBDayCalendarError: 'Para algunas fechas para calcular el pronóstico no es posible, ya que la fecha estimada antes de esa fecha el padre',
      boy: 'El niño',
      girl: 'La nina',
      boyorgirl: 'El niño o la niña con igual probabilidad',
      gender: 'Género',
      calendarHeader: "Calendario probabilidad de concebir un niño o una niña",
      methodsListPanelTitle:"Usar métodos en el cálculo",
      calendarFooter: 'Leyenda',
      precision: 'Confianza',
      powerindex: 'El método de antigüedad la sangre y el método japonés le permiten calcular la confianza en el pronóstico.',
      shareUs: "Recomienda BabyCalc a tus amigos",
      writeDevsTitle: "Escribe a los desarrolladores",
      writeDevsText1: "¿Alguna pregunta?",
      writeDevsText2: "¡Envíenos un correo electrónico!",
      donateDevsTitle: "Donar",
      donateDevsText1: "Si te gusta BabyCalc, puedes apoyar financieramente a los desarrolladores con la traducción de PayPal",
      donateDevsText2: "¡Muchas gracias!",
      donateDevsText3: "Apoyar a los desarrolladores financieramente",
      disclaimer: '¡Atención! La calculadora se basa en métodos de cálculo no confirmados por la investigación médica oficial y no garantiza una precisión del 100%.',
      developersAndDonate: "Contacte a los desarrolladores y Donar",
      mailButton:'Enviar correo electrónico',
      donateButton: 'Enviar transferencia de PayPal',
      ContentH2: "Métodos de predicción de género fetal",
      ContentP1_1:"La medicina moderna le permite determinar con precisión el género del niño dentro de unas pocas semanas después de la concepción. Sin embargo, la cuestión de qué género le interesaba al futuro bebé a las madres mucho antes de la aparición de los ultrasonidos y los análisis de sangre. Así que había ",
      ContentP1_2:"varios métodos para predecir el género del niño",
      ContentP1_3:", basados en la astrología, observaciones centenarias y patrones observables. Por supuesto, ninguno de estos métodos garantiza el 100% de precisión, sin embargo, la mayoría de las madres notan la fidelidad de las técnicas de pronóstico tradicionales.",
      ContentP2:"En esta página, puede calcular el género del feto usando los 3 métodos tradicionales más populares:",
      ContentP3:"Todo lo que necesitas hacer es ingresar las fechas de nacimiento de tus padres. Si conoce la fecha de la concepción, puede predecir el género del niño de tres maneras a la vez. Si solo está planeando un embarazo, seleccione el modo \"construir un calendario de pronóstico\". La aplicación mostrará el género más probable del niño para cada día de concepción.",
      ContentP4:"El pronóstico del calendario se puede calcular utilizando cualquiera de los métodos propuestos. Puede seleccionar los tres o marcar solo unos pocos. El pronóstico del calendario se puede ver de forma simplificada o mostrar los datos de cada método por separado.",
      ContentP5:"Para los métodos \"renovación de sangre\" y \"tabla japonesa\", el pronóstico indica confianza. Mientras más confianza, más probable es la aparición de un niño del género especificado.",
      ContentP6:"Dado que los métodos para predecir el género no se basan en investigaciones médicas precisas y se crearon independientemente el uno del otro, en algunos casos los resultados de su cálculo no coinciden.",
      ContentP7:"Uno de los métodos más simples para predecir el género de un feto es por la \"edad\" de la sangre. Se supone que en los hombres, se produce una renovación completa de la composición de la sangre cada 4 años. Y para las mujeres, cada 3 años. Para averiguar la \"edad de la sangre\", es necesario dividir la edad del padre entre 4 y la edad de la madre entre 3. Desechando la parte entera, obtenemos la \"edad de la sangre\" de cada uno de los padres. En otras palabras, el número de ciclos completos de actualización no se tiene en cuenta. Si la sangre de la madre es \"más joven\", es decir, actualizada más tarde que la sangre de su padre, habrá una niña. Si la sangre del padre es \"más joven\", nacerá un niño.",
      ContentP8:"La gran pérdida de sangre puede cambiar el ciclo natural de la renovación de la sangre. Si uno de los padres se sometió a cirugía, donación o transfusión de sangre, entonces, en lugar de la fecha de nacimiento, se debe indicar la fecha de la última pérdida de sangre. Este será el comienzo del ciclo de renovación de la sangre.",
      ContentP9:"El análisis de las revisiones de esta metodología en foros para mujeres embarazadas muestra que la precisión de tal pronóstico es aproximadamente del 62%.",
      ContentP10:"Esta técnica de predicción de género es especialmente popular entre las mujeres embarazadas en Rusia, Ucrania y Bielorrusia.",
      ContentP11:"En China, el método del calendario lunar para predecir el género de un feto se ha generalizado. Este método se basa en una tabla antigua compilada hace más de 1000 años. La tabla se calcula para la edad de la madre de 18 a 45 años. En él, para cada edad y mes en que se produjo la concepción, se indica el género del feto. La edad del padre no se usa para el cálculo.",
      ContentP12:"Esta tabla es fácil de encontrar en Internet. Sin embargo, debe tenerse en cuenta que para el cálculo correcto, debe especificar la edad y el mes de la concepción de acuerdo con el calendario lunar chino. La edad y la fecha de concepción en el calendario lunar y el europeo no coinciden. Esto se debe al hecho de que, según el calendario lunar, la edad en el momento del nacimiento ya es de 1 año, y no se agrega el día del nacimiento, sino en la fiesta nacional de la primavera o el Año Nuevo chino.",
      ContentP13:"BabyCalc traducirá automáticamente sus fechas al calendario lunar y realizará el cálculo correcto.",
      ContentP14:"Este método es utilizado por muchas familias chinas que quieren un hijo de cierto género.",
      ContentP15:"El método japonés para predecir el género del niño es similar al chino, pero también tiene en cuenta la fecha de nacimiento del padre. Incluye 2 tablas. En la primera tabla para cada pareja, \"mes de nacimiento del padre - mes de nacimiento de la madre\" contiene un número. En la segunda tabla, para cada número de la primera tabla y el mes calendario, se indica la probabilidad de concebir un niño o niña. Por lo tanto, el método japonés le permite planificar el género del feto para cualquier período de tiempo.",
      ContentP16:"Encontrar tablas de concepción japonesas en Internet es fácil. Para usarlos, no es necesario traducir las fechas al calendario lunar.",
      ContentP17:"Las encuestas muestran que la precisión del método japonés es del 70-80%.",
      ContentP18:"Es imposible planificar el sexo del niño, como afirma la medicina oficial. Sin embargo, no muchas parejas notan que han utilizado con éxito diversas técnicas \"populares\" para concebir una hija o un hijo. Entonces, en China, muchas parejas planean la fecha de la concepción de acuerdo con el calendario lunar, y en Rusia intentan predecir, calculando la \"edad\" de la sangre de los padres.",
      ContentP19:"Si está planeando un bebé, con la ayuda de BabyCalc puede crear un calendario, que marcará las fechas en que es más probable que conciba una niña o un niño. Para crear un pronóstico, seleccione el modo \"Crear calendario de pronóstico\", ingrese las fechas de nacimiento de los padres. Puede seleccionar uno o varios métodos para calcular el pronóstico, marcando los métodos necesarios a la izquierda del calendario.",
      ContentP20:"Sin embargo, no se tome demasiado en serio esta planificación: ninguno de los métodos utilizados en BabyCalc ha sido confirmado por investigaciones científicas. Piense en el pronóstico solo como información entretenida.",
      ContentL1:"renovación de sangre,",
      ContentL2:"tabla de bebé chino,",
      ContentL3:"tabla de bebé japonesa.",
      ContentH3_1: "¿Cómo funciona la predicción de género?",
      ContentH3_2: "¿Por qué las previsiones para diferentes métodos no coinciden?",
      ContentH3_3: "¿Qué métodos de cálculo usa este sitio?",
      ContentH4_1: "Método de renovación de sangre",
      ContentH4_2: "Calendario lunar chino",
      ContentH4_3: "Tabla japonesa",
      ContentH3_4: "¿Cómo planificar el género del niño?",
      menu: "Menú de navegación",
      menuMain: "Calculadora de género de bebés",
      menuAbout: "Cómo BabyCalc funciona",
      menuMethods: "Métodos de predicción de género.",
      menuBlood:"Género de un niño para la renovación de sangre",
      menuChina:"La tabla china",
      menuJapan:"La tabla japonesa",
      menuSell: "BabyCalc integrado para su sitio web",
      chinese1: "Calendario china para saber el genero del bebe",
      chinese2: "La tabla china para determinar el sexo del niño según la edad de la madre se conoce desde hace más de 700 años. Su original se ha conservado y todavía se almacena en el Instituto de Beijing. Reconocido en China, el calendario de género de bebés ahora es popular en todo el mundo. Se utiliza tanto para averiguar el sexo de un niño de la mesa como para elegir el día más exitoso para concebir un niño o una niña.",
      chinese3: "A pesar de que la tabla china del sexo del niño no se basa en teorías médicas o científicas, más del 75% de las madres notan su fiabilidad.",
      chinese4: "¿Cómo determinar el sexo del niño según la fecha de concepción?",
      chinese5: "Para averiguar el sexo del niño de la tabla, primero debe calcular la edad lunar de la madre. El hecho es que el calendario chino para determinar el sexo de un niño se basa en el calendario lunar chino. Según él, la edad de la madre será uno o dos años más que la edad según el calendario europeo.",
      chinese6: "Puede averiguar su edad lunar en línea usando la calculadora en esta página.",
      chinese7: "A continuación, debe averiguar el mes de la concepción en el calendario lunar. Para hacer esto, ingrese la fecha estimada de concepción en el campo a continuación.",
      chinese8: "Conociendo su edad lunar y el mes de la concepción, solo queda encontrar la celda apropiada en la tabla, indicará el género más probable del niño.",
      chinese9: "Es mucho más fácil calcular el sexo del bebé en línea usando el calendario chino de embarazo, en la página principal de este sitio.",
      chinese10: "Calendario de concepción china",
      chinese11: "Si desea concebir un hijo de un determinado género, use la función /'Calendario de concepción/' en la página principal de este sitio. La calculadora calculará los intervalos más favorables para la concepción de un niño o niña, no solo para 2020, sino también para cualquier intervalo que necesite.",
      chinese12: "El calendario reflejará los períodos en los que la concepción de un niño o niña es más probable.",
      chinese13: "No olvide que la determinación del género en el calendario chino no tiene una precisión del 100% y puede usarse exclusivamente para fines de entretenimiento.",
      lunarSolar1:"Descubre la edad lunar",
      lunarSolar2:"Introduzca su fecha de nacimiento",
      lunarSolar3:"Tu edad lunar",
      lunarSolar4:"fecha de concepción",
      lunarSolar5:"Mes lunar de la concepción",
      lunarSolar6:"Calcular el mes lunar de la concepción",
      chinaTable1:"Tabla de bebé chino",
      chinaTable2:"Edad lunar de la madre",
      chinaTable3:"Mes de la concepción",
      blood1:"Género de un niño para la renovación de sangre",
      blood2:"La determinación del sexo del género por la sangre se basa en el supuesto de que la sangre, las membranas mucosas y otros tejidos de una persona se actualizan por completo en el proceso de la vida con cierta frecuencia. Para los hombres, el período de renovación completa de la sangre y los tejidos dura 4 años, y para las mujeres: 3 años. Si en el momento de la concepción la sangre de una mujer es \"más joven\" que la sangre de un hombre, nacerá una niña. Si la sangre de un hombre se ha actualizado recientemente, y las mujeres, hace mucho tiempo, nacerá un niño. En otras palabras, el niño tendrá el género del padre cuya sangre es \"más joven\".",
      blood3:"Al determinar el sexo del niño por la sangre, debe tenerse en cuenta que si uno o ambos padres sufrieron una pérdida importante de sangre en el pasado, en lugar de la fecha de nacimiento, la fecha de la pérdida de sangre debe usarse en los cálculos. Ejemplos de situaciones en las que se produce una pérdida importante de sangre: lesiones graves, transfusión de sangre, donación de sangre, parto, cirugía grave.",
      blood4:"¿Cómo calcular el sexo del niño para la renovación de sangre?",
      blood5_1:"Divida la edad del padre por 4, y la edad de la madre por 3.",
      blood5_2:"Deseche las partes enteras de los números obtenidos (el número de ciclos completos no afecta la \"edad\" de la sangre) y compare los residuos.",
      blood5_3:"Quien tiene un equilibrio menor, tiene una sangre más \"joven\", por lo tanto, este género será un niño.",
      blood6:"Para evitar cálculos manuales, use la calculadora de actualización de sangre en la página de inicio de BabyCalc. Es suficiente ingresar las fechas de nacimiento de los padres y la fecha estimada de concepción, y la calculadora calculará el género del niño en línea.",
      blood7:"A diferencia de muchas otras calculadoras de género sanguíneo, BabyCalc le permite calcular la confianza en el pronóstico del género del bebé. La confianza en el pronóstico se calcula en función de la diferencia en las \"edades\" de la sangre. Entonces, si la diferencia es pequeña, el cálculo puede ser incorrecto, ya que las características individuales del cuerpo pueden ralentizar o acelerar el proceso de renovación de la sangre.",
      blood8:"Concepción de renovación sanguínea",
      blood9:"La determinación del género por la sangre a menudo se usa para planificar la concepción de un bebé. Por ejemplo, si una pareja sueña con un niño, la concepción de un niño se puede planificar para un período en que la sangre del hombre sea \"más joven\".",
      blood10:"Si desea conocer los períodos más favorables para la concepción de una niña o un niño, cree un calendario de concepción individual en la página principal de este sitio. El programa calculará automáticamente los períodos de la concepción más probable de un niño o niña para 2020 o cualquier otro año.",
      blood11:"¡Atención! La determinación del género del niño por la sangre no se basa en investigaciones médicas oficiales y no tiene una precisión del 100%. Todos los pronósticos se presentan solo con fines de entretenimiento y no pueden servir como base para decisiones serias.",
      japTableHeader1:"Tabla japonesa del bebé, parte 1",
      japTableHeader2:"Tabla japonesa del bebé, parte 2",
      japTable1:"Fecha de nacimiento hombre",
      japTable2:"Fecha de nacimiento mujer",
      japTable3:"El número de la primera tabla",
      japTable4:"Mes de concepción",
      japanese1:"Este es uno de los métodos más populares y fáciles de averiguar a quién espera la futura madre: un niño o una niña. Para saber el género del niño, solo se requerirán las fechas de nacimiento de los padres.",
      japanese2:"Cómo predecir el género del bebé por la tabla japonesa de bebés?",
      japanese3:"La mesa de género japonesa para bebés tiene dos partes.  El primero contiene números auxiliares, el segundo contiene las probabilidades del nacimiento de un niño o niña.",
      japanese4:"Para determinar el género del niño en el calendario japonés, necesita:",
      japanese4_1:"En la primera tabla, encuentre la columna con el mes de nacimiento de la madre y la fila con el mes de nacimiento del padre.",
      japanese4_2:"Recuerde el número en la intersección de la columna y la fila",
      japanese4_3:"En la segunda tabla, encuentre la fila con el número de la primera tabla y la columna con el mes de la concepción. En su intersección, se indica el género del futuro bebé y se indica la probabilidad de la exactitud del pronóstico. Ambos géneros están indicados en algunas celdas, lo que significa que la concepción de un niño y una niña es igualmente probable.",
      japanese5:"Planificación de género japonesa",
      japanese6:"Si observa de cerca la tabla, puede ver que algunos meses están marcados por una alta probabilidad de dar a luz a un niño o niña, mientras que otros tienen una razón de probabilidades aproximadamente igual. Si una pareja sueña con un niño de cierto género, debe elegir los meses con la mayor diferencia en la probabilidad de concebir un hijo. Por ejemplo, para una pareja a la que corresponde el número 7 en la primera tabla, las mayores posibilidades de concebir un niño a los 2 y 10 meses del año, y una niña a los 3 y 11.",
      japanese7:"Calendario de embarazo japonés 2020",
      japanese8:"Con BabyCalc, puede crear un calendario de concepción individual para una mesa japonesa de forma gratuita. En la página principal, ingrese las fechas de nacimiento de los padres y seleccione el modo \"Calendario de concepción\". El programa calculará automáticamente los períodos más favorables para la concepción de un niño o niña de acuerdo con el calendario japonés, así como el calendario lunar chino y el método de actualización de la sangre. Puede crear un pronóstico para cualquier período.",
      japanese9:"La precisión del calendario japonés de embarazos",
      japanese10:"La tabla japonesa de bebés ha sido popular en muchos países del mundo. En Asia, se la considera la forma más precisa de predecir el género del niño.",
      japanese11:"Las revisiones de la tabla japonesa de bebés de foros y grupos de redes sociales sugieren que alrededor del 80% de los pronósticos son correctos.",
      japanese12:"¿Cuál es la base para determinar el género mediante una tabla de bebé japonesa?",
      japanese13:"El género del niño depende del conjunto de cromosomas que contiene el esperma. En las mujeres, el óvulo siempre tiene el mismo conjunto de cromosomas, pero las células masculinas pueden transportar tanto la combinación masculina de cromosomas como la femenina. Este es un hecho científico comprobado.",
      japanese14:"La medicina moderna afirma que es imposible predecir de antemano qué conjunto de cromosomas llevará el esperma que ha fertilizado el óvulo. La opinión opuesta fue expresada por un grupo de científicos japoneses. Creen que en algunos ciclos de tiempo, los más activos son las células masculinas con un conjunto masculino de cromosomas, y en otros, con uno femenino. Esta suposición sirvió de base para la compilación del calendario japonés de embarazos.",
      japanese15:"¡Atención! El método para determinar el género del bebé de acuerdo con la tabla japonesa no tiene una certeza del 100% y no está confirmado por la investigación médica oficial.",
      japanese16:"Todos los pronósticos en el sitio web de BabyCalc se proporcionan solo con fines de entretenimiento y no pueden servir como base para tomar decisiones serias.",
      p404_title:"Página no encontrada",
      p404_subtitle:"La página que estás buscando ya no existe",
      goToCalc:"Ir a la calculadora de género del bebé y el calendario de embarazo"
    })
  ]
})
