import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from './../node_modules/vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
  initial: 'en',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('ru').create({
      langName: 'Русский',
      title: 'BabyCalc - калькулятор прогнозирования пола ребенка',
      aboutPart1:'Здесь вы можете спрогнозировать пол будущего ребенка.  Для расчетов используется теория обновления крови, китайский лунный календарь  и традиционный японский метод.',
      aboutPart2:'Зная предполагаемую дату зачатия, вы можете узнать кого вы, вероятнее всего ждете - мальчика или девочку.  Также вы можете построить календарь,  в котором будут указан наиболее вероятный пол ребенка для каждого дня зачатия. Эта функция будет полезна тем, кто планирует беременность.',
      aboutPart3:'Для расчетов используется теория обновления крови, китайский лунный календарь  и традиционный японский метод. Вы можете использовать в расчетах все три метода сразу или выбрать предпочтительные.',
      modeSectionHeader: 'Выберите режим',
      mbdayTitle: 'Дата рождения матери',
      fbdayTitle: 'Дата рождения отца',
      concdayTitle: 'Дата зачатия',
      datemodeTitle: 'Спрогнозировать пол ребенка по дате зачатия',
      calendarmodeTitle: 'Построить календарь прогнозов',
      methodslistTitle: 'Методы расчета',
      bloodMethodName: 'Старшинства крови',
      chineseMethodName: 'Китайский лунный календарь',
      japaneseMethodName: 'Японская таблица',
      bloodMethodFullName: 'Рассчитано по методу старшинства крови',
      chineseMethodFullName: 'Рассчитано по китайскому лунному календарю',
      japaneseMethodFullName: 'Рассчитано по японской таблице',
      displayOverallTitle: 'Показывать обобщенный прогноз',
      displaySeparatedTitle: 'Показывать результаты методов отдельно',
      methodsWarn: 'Выберите как минимум один метод',
      datesWarn: 'Чтобы получить прогноз, укажите даты рождения родителей',
      chineseAgeWarn: 'Расчет по китайскому лунному календарю доступен для возраста матери от 18 до 45 лет. Указанный вами возраст не входит в этот промежуток и прогноз по китайскому лунному календарю не рассчитан.',
      bloodMethodDescription: 'Метод, основанный на теории обновления крови. Мужская кровь обновляется раз в 4 года, женская - раз в три. Чья кровь моложе на момент зачатия, такого пола будет ребенок. Если один из родителей перенес крупную кровопотерю (роды, операция, переливание крови), для правильного расчета вместо даты рождения следует указать дату кровопотери.',
      chineseMethodDescription: 'Расчет по китайскому лунному календарю определяет пол будущего ребенка по возрасту матери и месяцу зачатия. Этот метод популярен в Китае среди тех, кто планирует беременность и хочет ребенка определенного пола.',
      japaneseMethodDescription: 'Японская система прогнозирования, которая рассчитывает вероятность появления мальчика или девочки, основываясь на возрасте отца и матери, а также месяце зачатия. Для каждой комбинации метод рассчитывает вероятность появления мальчика или девочки. Этот метод популярен в Японии.',
      readMore:"Подробнее",
      confidenceBlood: "Уверенность в прогнозе рассчитывается на основании разницы возрастов крови отца и матери. Чем больше разница возрастов, тем выше уверенность в прогнозе",
      confidenceChinese: 'Этот метод не рассчитывает уверенность в прогнозе',
      confidenceJapanese: 'Уверенность в прогнозе вычисляется на основании данных таблицы.',
      chineseAgeCalendarError: 'Для некоторых дат не удалось рассчитать прогноз по китайскому лунному календарю, так как лунный возраст матери в эти даты не входит в диапазон от 18 до 45 лет',
      boy: 'Мальчик',
      girl: 'Девочка',
      motherBDayError:'Дата рождения матери позже даты зачатия. Введите верные даты для расчета.',
      fatherBDayError: 'Дата рождения отца позже даты зачатия. Введите верные даты для расчета.',
      motherBDayCalendarError:'Для некоторых дат рассчитать прогноз невозможно, так как расчетная дата раньше указанной даты рождения матери',
      fatherBDayCalendarError: 'Для некоторых дат рассчитать прогноз невозможно, так как расчетная дата раньше указанной даты рождения отца',
      boyorgirl: 'Мальчик или девочка с равной вероятностью',
      gender: 'Пол',
      precision: 'Уверенность в прогнозе',
      calendarHeader: 'Календарь вероятности зачатия мальчика или девочки',
      methodsListPanelTitle:"Использовать в расчете методы",
      calendarFooter: 'Условные обозначения',
      powerindex: 'Метод обновления крови и японский метод позволяют рассчитать уверенность в прогнозе.',
      shareUs: "Рекомендуйте калькулятор друзьям",
      writeDevsTitle: "Написать разработчикам",
      writeDevsText1: "Есть вопросы?",
      writeDevsText2: "Напишите нам на электронную почту!",
      donateDevsTitle: "Поддержать разработчиков",
      donateDevsText1: "Если вам нравится BabyCalc, вы можете  материально поддержать разработчиков переводом PayPal",
      donateDevsText2: "Спасибо!",
      donateDevsText3: "Поддержите разработчиков материально",
      disclaimer: 'Внимание! Калькулятор основан на методах расчета, не подтвержденных официальными медицинскими исследованиями и не гарантирует 100% точности!',
      developersAndDonate: "Связь с разработчиками и Donate",
      mailButton:'Отправить Email',
      donateButton: 'Отправить перевод PayPal',
      ContentH2: "Методы предсказания пола будущего ребенка",
      ContentP1:"Современная медицина позволяет с высокой точностью определить пол ребенка уже через несколько недель после зачатия. Однако вопрос о том, какого пола будущий малыш, интересовал мам задолго до появления УЗИ и анализов крови. Так появились различные методики предсказания пола ребенка - основанные на астрологии, многовековых наблюдениях и подмеченных закономерностях. Конечно, ни один из подобных методов не гарантирует 100%  точности, тем не менее большинство мам отмечает верность традиционных методик прогнозирования.",
      ContentP2:"На этой странице вы можете рассчитать пол будущего ребенка по 3 наиболее популярным традиционным методам:",
      ContentP3:"Все, что требуется сделать - ввести даты рождения родителей. Если вы знаете дату зачатия, вы можете спрогнозировать пол ребенка по трем методам сразу. Если же вы только планируете беременность, выберите режим «построить календарь прогнозов». Приложение покажет наиболее вероятный пол ребенка на каждый день зачатия. ",
      ContentP4:"Календарный прогноз можно рассчитать с использованием любых из предложенных методов. Вы можете выбрать все три, или отметить только некоторые. Календарный прогноз можно посмотреть в упрощенном виде, или отобразить данные по каждому методу  отдельно.",
      ContentP5:"Для методов «обновление крови» и «японская таблица» в прогнозе указывается уверенность. Чем больше уверенность, тем вероятнее появление ребенка указанного пола.",
      ContentP6:"Так как методики прогнозирования пола не основываются на точных медицинских исследованиях и создавались независимо друг от друга, в некоторых случаях результаты их расчета не совпадают.",
      ContentP7:"Одна из самых простых методик прогнозирования пола будущего ребенка - по «возрасту» крови.  Предполагается, что у мужчин полное обновление состава крови происходит раз в 4 года. А у женщин - раз в 3 года. Чтобы узнать «возраст крови», необходимо разделить возраст отца на 4, а возраст матери - на 3. Отбросив целую часть, получаем «возраст крови» каждого из родителей. Другими словами, количество полных циклов обновления не принимается во внимание. Если кровь матери «моложе», то есть обновилась позже, чем кровь отца - будет девочка. Если же «моложе» кровь отца - родится мальчик.",
      ContentP8:"Крупные потери крови могут сдвинуть естественный цикл обновления крови. Если один из родителей перенес операцию, донорство или переливание крови, то вместо даты рождения следует указать дату последней потери крови. Это будет началом отсчета цикла обновления крови.",
      ContentP9:"Анализ отзывов на эту методику на  форумах для беременных показывает, что точность подобного прогноза приблизительно равна 62%.",
      ContentP10:"Эта методика прогнозирования пола особенно популярна среди будущих мам в России, Украине и Беларуси.",
      ContentP11:"В Китае широкое распространение получил метод прогнозирования пола будущего ребенка по лунному календарю. Этот метод основан на древней таблице, составленной более 1000 лет назад.  Таблица рассчитана для возраста матери от 18 до 45 лет. В ней для каждого возраста и месяца, в котором произошло зачатие, указан пол будущего ребенка. Возраст отца не используется для расчета.",
      ContentP12:"Данную таблиц несложно найти в интернете. Однако следует учитывать, что для правильного расчета требуется указать возраст и месяц зачатия по китайскому лунному календарю. Возраст и дата зачатия по лунному календарю и по европейскому не совпадают. Это обусловлено тем, что по лунному календарю возраст на момент рождения уже составляет 1 год, и прибавляется не в день рождения, а в национальный праздник Весны или Китайский новый год.",
      ContentP13:"BabyCalc автоматически переведет указанные вами даты в лунный календарь и выполнит верный расчет.",
      ContentP14:"Этот метод используется многими китайскими семьями, которые хотят ребенка определенного пола.",
      ContentP15:"Японский метод прогнозирования пола ребенка схож с китайским, но он также учитывает дату рождения отца. Он включает 2 таблицы. В первой таблице для каждой пары «месяц рождения отца - месяц рождения матери» содержится число. Во второй таблице для каждого числа из первой таблицы и календарного месяца указана вероятность зачатия мальчика или девочки. Таким образом, японский метод позволяет «спланировать» пол будущего ребенка на любой период времени.",
      ContentP16:"Найти японские таблицы зачатия в интернете не составляет труда. Чтобы воспользоваться ими, не нужно переводить даты в лунный календарь. ",
      ContentP17:"Результаты опросов показывают, что точность японского метода составляет 70-80%.",
      ContentL1:"обновление крови,",
      ContentL2:"китайский лунный календарь,",
      ContentL3:"традиционная японская таблица.",
      ContentH3_1: "Как работает предсказание пола ребенка?",
      ContentH3_2: "Почему прогнозы по разным методам не совпадают?",
      ContentH3_3: "Какие методы расчета использует этот сайт?",
      ContentH4_1: "Метод обновления крови",
      ContentH4_2: "Китайский лунный календарь",
      ContentH4_3: "Японская таблица"

    }),

    new MLanguage('en').create({
      langName: 'English',
      title: 'BabyCalc - baby gender prediction calculator',
      aboutPart1:'Here you can predict the gender of the future child. For calculations, the theory of blood renewal, the Chinese lunar calendar and the traditional Japanese method are used.',
      aboutPart2:'Knowing the estimated date of conception, you can find out who you are most likely waiting for - a boy or a girl. You can also build a calendar that will indicate the most likely gender of the child for each day of conception. This feature will be useful for those planning a pregnancy.',
      aboutPart3:'For calculations, the theory of blood renewal, the Chinese lunar calendar and the traditional Japanese method are used. You can use all three methods in the calculations at once or choose preferred ones.',
      modeSectionHeader: 'Choose mode',
      mbdayTitle: 'Mother\'s date of birth',
      fbdayTitle: ' Father\'s date of birth',
      concdayTitle: 'Conception date',
      datemodeTitle: 'Predict the gender of the baby by the date of conception',
      calendarmodeTitle: 'Build a forecast calendar',
      methodslistTitle: 'Calculation methods',
      bloodMethodName: 'Blood seniority',
      chineseMethodName: 'Chinese moon calendar',
      japaneseMethodName: 'Japanese chart',
      bloodMethodFullName: 'Calculated by the method of blood seniority',
      chineseMethodFullName: 'Calculated by the Chinese lunar calendar',
      japaneseMethodFullName: 'Calculated by the Japanese table',
      displayOverallTitle: 'Show generalized forecast',
      displaySeparatedTitle: 'Show method results separately',
      methodsWarn: 'Please select at least one method',
      datesWarn: 'To get a forecast, enter the date of birth of parents',
      chineseAgeWarn: 'Calculation according to the Chinese lunar calendar is available for mother\'s age from 18 to 45 years. The age you specified is not included in this period and the forecast for the Chinese lunar calendar is not calculated.',
      bloodMethodDescription: 'A method based on the theory of blood renewal. Male blood is renewed every 4 years, female blood - every three years. Whose blood is younger at the time of conception, this gender will be a child. If one of the parents suffered a major blood loss (childbirth, surgery, blood transfusion), for the correct calculation, the date of blood loss should be entered instead of the date of birth.',
      chineseMethodDescription: 'The calculation according to the Chinese lunar calendar determines the gender of the unborn child according to the age of the mother and the month of conception. This method is popular in China among those who are planning a pregnancy and want a baby of a certain gender.',
      japaneseMethodDescription: 'A Japanese forecasting system that calculates the probability of a boy or girl based on the age of the father and mother, as well as the month of conception. For each combination, the method calculates the probability of a boy or girl. This method is popular in Japan.',
      confidenceBlood: "Confidence in the forecast is calculated based on the difference between the age of blood of mother and father. The greater the age difference, the higher the confidence in the forecast.",
      confidenceChinese: 'This method does not calculate confidence in the forecast.',
      confidenceJapanese: "Confidence in the forecast is calculated based on the data in the table.",
      chineseAgeCalendarError: 'For some dates, it was not possible to calculate the forecast for the Chinese lunar calendar, since the lunar age of the mother on these dates is not in the range from 18 to 45 years',
      motherBDayError:'Mother\'s date of birth later than conception date. Enter the correct date for the calculation.',
      fatherBDayError: 'Father\'s date of birth later than conception date. Enter the correct date for the calculation.',
      motherBDayCalendarError:'For some dates to calculate the forecast is not possible, since the estimated date before that date the birth mother',
      fatherBDayCalendarError: 'For some dates to calculate the forecast is not possible, since the estimated date before that date the birth father',
      boy: 'Boy',
      girl: 'Girl',
      boyorgirl: 'Boy or girl with equal probability',
      gender: 'Gender',
      calendarHeader: 'Calendar probability of conceiving a boy or girl',
      methodsListPanelTitle:"Use methods in the calculation",
      calendarFooter: 'Legend',
      precision: 'Confidence',
      powerindex: 'The blood seniority method and the Japanese method make it possible to calculate confidence in the prognosis.',
      shareUs: "Recommend the calculator to friends",
      writeDevsTitle: "Write to developers",
      writeDevsText1: "Have questions?",
      writeDevsText2:"Email us!",
      donateDevsTitle: "Donate",
      donateDevsText1: "If you like BabyCalc, you can financially support the developers PayPal transfer",
      donateDevsText2: "Thank you so much!",
      donateDevsText3: "Support developers financially",
      disclaimer: 'Attention! The calculator is based on calculation methods not confirmed by official medical research and does not guarantee 100% accuracy!',
      developersAndDonate: "Contact developers and Donate",
      mailButton:'Send Email',
      donateButton: 'Send PayPal transfer',
      ContentH2: "Methods of predicting the gender of the child",
      ContentP1:"Modern medicine allows you to accurately determine the gender of the child within a few weeks after conception. However, the question of what gender the future baby was interested in by mothers long before the appearance of ultrasound and blood tests. So there were various methods for predicting the gender of the child - based on astrology, centuries-old observations and observable patterns. Of course, none of these methods guarantees 100% accuracy, however, most mothers note the fidelity of traditional forecasting techniques.",
      ContentP2:"On this page, you can calculate the gender of the child using the 3 most popular traditional methods:",
      ContentP3:"All you need to do is enter your parents ’birth dates. If you know the date of conception, you can predict the gender of the child in three ways at once. If you are just planning a pregnancy, select the \"build a forecast calendar\" mode. The application will show the most likely gender of the child for each day of conception.",
      ContentP4:"The calendar forecast can be calculated using any of the proposed methods. You can select all three, or mark only a few. The calendar forecast can be viewed in a simplified form, or display data for each method separately.",
      ContentP5:"For the methods \"blood renewal\" and \"Japanese table\", the forecast indicates confidence. The more confidence, the more likely the appearance of a child of the specified gender.",
      ContentP6:"Since the methods for predicting gender are not based on accurate medical research and were created independently of each other, in some cases the results of their calculation do not match.",
      ContentP7:"One of the simplest methods for predicting the gender of a child is by the \"age\" of blood. It is assumed that in men, a complete renewal of the blood composition occurs every 4 years. And for women - every 3 years. To find out the \"age of blood\", it is necessary to divide the age of the father by 4, and the age of the mother by 3. Discarding the integer part, we obtain the \"age of blood\" of each of the parents. In other words, the number of full update cycles is not taken into account. If the mother’s blood is \"younger\", that is, updated later than her father’s blood, there will be a girl. If the father’s blood is \"younger\", a boy will be born.",
      ContentP8:"Large blood loss can shift the natural cycle of blood renewal. If one of the parents has undergone surgery, donation or blood transfusion, then instead of the date of birth, the date of the last blood loss should be indicated. This will be the start of the blood renewal cycle.",
      ContentP9:"Analysis of reviews of this methodology on forums for pregnant women shows that the accuracy of such a forecast is approximately 62%.",
      ContentP10:"This gender prediction technique is especially popular among expectant mothers in Russia, Ukraine and Belarus.",
      ContentP11:"In China, the lunar calendar method for predicting the gender of the child has become widespread. This method is based on an ancient table compiled more than 1000 years ago. The table is calculated for mother's age from 18 to 45 years. In it, for each age and month in which the conception occurred, the the gender of the child is indicated. Father's age is not used for calculation.",
      ContentP12:"This table is easy to find on the Internet. However, it should be borne in mind that for the correct calculation, you must specify the age and month of conception according to the Chinese lunar calendar. The age and date of conception on the lunar calendar and the European do not match. This is due to the fact that according to the lunar calendar, the age at the time of birth is already 1 year, and is added not on the day of birth, but on the national holiday of Spring or Chinese New Year.",
      ContentP13:"BabyCalc will automatically translate your dates into the lunar calendar and perform the correct calculation.",
      ContentP14:"This method is used by many Chinese families who want a child of a certain gender.",
      ContentP15:"The Japanese method for predicting the gender of the child is similar to the Chinese, but it also takes into account the date of birth of the father. It includes 2 tables. In the first table for each pair, \"father’s month of birth - mother’s month of birth\" contains a number. In the second table, for each number from the first table and the calendar month, the probability of conceiving a boy or girl is indicated. Thus, the Japanese method allows you to plan the gender of the child for any period of time.",
      ContentP16:"Finding Japanese baby charts on the Internet is easy. To use them, you do not need to translate dates into the lunar calendar.",
      ContentP17:"Surveys show that the accuracy of the Japanese method is 70-80%.",
      ContentL1:"blood renewal,",
      ContentL2:"chinese lunar calendar,",
      ContentL3:"traditional japanese table.",
      ContentH3_1: "How does gender prediction work?",
      ContentH3_2: "Why are the forecasts for different methods do not match?",
      ContentH3_3: "What calculation methods does this site use?",
      ContentH4_1: "Blood renewal method",
      ContentH4_2: "Chinese lunar calendar",
      ContentH4_3: "Japanese table"


    }),
    new MLanguage('es').create({
      langName: 'Español',
      title: 'BabyCalc - calculadora de predicción de género de bebé',
      aboutPart1:'Aquí puedes predecir el género del feto. Para los cálculos, se utilizan la teoría de la renovación de la sangre, el calendario lunar chino y el método tradicional japonés.',
      aboutPart2:'Conociendo la fecha estimada de la concepción, puede averiguar a quién está esperando: un niño o una niña. También puede crear un calendario que indique el género más probable del niño para cada día de concepción. Esta característica será útil para quienes planean un embarazo.',
      aboutPart3:'Para los cálculos, se utilizan la teoría de la renovación de la sangre, el calendario lunar chino y el método tradicional japonés. Puede usar los tres métodos en los cálculos a la vez o elegir los preferidos.',
      modeSectionHeader: 'Elige un modo',
      mbdayTitle: 'Fecha de nacimiento de la madre',
      fbdayTitle: 'Fecha de nacimiento del padre',
      concdayTitle: 'Fecha de la concepción',
      datemodeTitle: 'Predecir el género del niño por la fecha de concepción',
      calendarmodeTitle: 'Crea un calendario de previsión',
      methodslistTitle: 'Métodos de cálculo',
      bloodMethodName: 'Antigüedad de sangre',
      chineseMethodName: 'Calendario lunar chino',
      japaneseMethodName: 'La tabla japonesa',
      bloodMethodFullName: 'Calculado por el método de antigüedad de sangre',
      chineseMethodFullName: 'Calculado según el calendario lunar chino',
      japaneseMethodFullName: 'Calculado por la tabla japonesa',
      displayOverallTitle: 'Mostrar pronóstico generalizado',
      displaySeparatedTitle: 'Mostrar los resultados del método por separado',
      methodsWarn: 'Por favor seleccione al menos un método',
      chineseAgeWarn: 'El cálculo según el calendario lunar chino está disponible para la edad de la madre de 18 a 45 años. La edad que especificó no se incluye en este período y no se calcula el pronóstico para el calendario lunar chino.',
      datesWarn: 'Para obtener un pronóstico, especifique las fechas de nacimiento de los padres',
      bloodMethodDescription: 'El método se basa en la teoría de la renovación sanguínea. La sangre masculina se renueva cada 4 años, la sangre femenina, cada tres años. Cuya sangre es más joven al momento de la concepción, tal género tendrá un hijo',
      chineseMethodDescription: 'El cálculo según el calendario lunar chino determina el gender del feto según la edad de la madre y el mes de la concepción. Este método es popular en China entre quienes planean un embarazo y quieren un bebé de cierto género.',
      japaneseMethodDescription: 'Un sistema de pronóstico japonés que calcula la probabilidad de un niño o niña en función de la edad del padre y la madre, así como el mes de la concepción. Para cada combinación, el método calcula la probabilidad de un niño o niña. Este método es popular en Japón.',
      confidenceBlood: "La confianza en el pronóstico se calcula en función de la diferencia en las edades de la sangre del padre y la madre. Cuanto mayor es la diferencia de edad, mayor es la confianza en el pronóstico.",
      confidenceChinese: 'Este método no calcula la confianza en el pronóstico.',
      confidenceJapanese: "La confianza en el pronóstico se calcula con base en los datos de la tabla.",
      chineseAgeCalendarError: 'Para algunas fechas, no fue posible calcular el pronóstico para el calendario lunar chino, ya que la edad lunar de la madre en estas fechas no está en el rango de 18 a 45 años.',
      motherBDayError:'Fecha de nacimiento de la madre posterior a la fecha de concepción. Introduzca la fecha correcta para el cálculo.',
      fatherBDayError: 'Fecha de nacimiento del padre posterior a la fecha de concepción. Introduzca la fecha correcta para el cálculo.',
      motherBDayCalendarError:'Para algunas fechas para calcular el pronóstico no es posible, ya que la fecha estimada antes de esa fecha la madre',
      fatherBDayCalendarError: 'Para algunas fechas para calcular el pronóstico no es posible, ya que la fecha estimada antes de esa fecha el padre',
      boy: 'El niño',
      girl: 'La nina',
      boyorgirl: 'El niño o la niña con igual probabilidad',
      gender: 'Género',
      calendarHeader: "Calendario probabilidad de concebir un niño o una niña",
      methodsListPanelTitle:"Usar métodos en el cálculo",
      calendarFooter: 'Leyenda',
      precision: 'Confianza',
      powerindex: 'El método de antigüedad la sangre y el método japonés le permiten calcular la confianza en el pronóstico.',
      shareUs: "Recomienda la calculadora a tus amigos",
      writeDevsTitle: "Escribe a los desarrolladores",
      writeDevsText1: "¿Alguna pregunta?",
      writeDevsText2: "¡Envíenos un correo electrónico!",
      donateDevsTitle: "Donar",
      donateDevsText1: "Si te gusta BabyCalc, puedes apoyar financieramente a los desarrolladores con la traducción de PayPal",
      donateDevsText2: "¡Muchas gracias!",
      donateDevsText3: "Apoyar a los desarrolladores financieramente",
      disclaimer: '¡Atención! La calculadora se basa en métodos de cálculo no confirmados por la investigación médica oficial y no garantiza una precisión del 100%.',
      developersAndDonate: "Contacte a los desarrolladores y Donar",
      mailButton:'Enviar correo electrónico',
      donateButton: 'Enviar transferencia de PayPal',
      ContentH2: "Métodos de predicción de género fetal",
      ContentP1:"La medicina moderna le permite determinar con precisión el género del niño dentro de unas pocas semanas después de la concepción. Sin embargo, la cuestión de qué género le interesaba al futuro bebé a las madres mucho antes de la aparición de los ultrasonidos y los análisis de sangre. Así que había varios métodos para predecir el género del niño, basados en la astrología, observaciones centenarias y patrones observables. Por supuesto, ninguno de estos métodos garantiza el 100% de precisión, sin embargo, la mayoría de las madres notan la fidelidad de las técnicas de pronóstico tradicionales.",
      ContentP2:"En esta página, puede calcular el género del feto usando los 3 métodos tradicionales más populares:",
      ContentP3:"Todo lo que necesitas hacer es ingresar las fechas de nacimiento de tus padres. Si conoce la fecha de la concepción, puede predecir el género del niño de tres maneras a la vez. Si solo está planeando un embarazo, seleccione el modo \"construir un calendario de pronóstico\". La aplicación mostrará el género más probable del niño para cada día de concepción.",
      ContentP4:"El pronóstico del calendario se puede calcular utilizando cualquiera de los métodos propuestos. Puede seleccionar los tres o marcar solo unos pocos. El pronóstico del calendario se puede ver de forma simplificada o mostrar los datos de cada método por separado.",
      ContentP5:"Para los métodos \"renovación de sangre\" y \"tabla japonesa\", el pronóstico indica confianza. Mientras más confianza, más probable es la aparición de un niño del género especificado.",
      ContentP6:"Dado que los métodos para predecir el género no se basan en investigaciones médicas precisas y se crearon independientemente el uno del otro, en algunos casos los resultados de su cálculo no coinciden.",
      ContentP7:"Uno de los métodos más simples para predecir el género de un feto es por la \"edad\" de la sangre. Se supone que en los hombres, se produce una renovación completa de la composición de la sangre cada 4 años. Y para las mujeres, cada 3 años. Para averiguar la \"edad de la sangre\", es necesario dividir la edad del padre entre 4 y la edad de la madre entre 3. Desechando la parte entera, obtenemos la \"edad de la sangre\" de cada uno de los padres. En otras palabras, el número de ciclos completos de actualización no se tiene en cuenta. Si la sangre de la madre es \"más joven\", es decir, actualizada más tarde que la sangre de su padre, habrá una niña. Si la sangre del padre es \"más joven\", nacerá un niño.",
      ContentP8:"La gran pérdida de sangre puede cambiar el ciclo natural de la renovación de la sangre. Si uno de los padres se sometió a cirugía, donación o transfusión de sangre, entonces, en lugar de la fecha de nacimiento, se debe indicar la fecha de la última pérdida de sangre. Este será el comienzo del ciclo de renovación de la sangre.",
      ContentP9:"El análisis de las revisiones de esta metodología en foros para mujeres embarazadas muestra que la precisión de tal pronóstico es aproximadamente del 62%.",
      ContentP10:"Esta técnica de predicción de género es especialmente popular entre las mujeres embarazadas en Rusia, Ucrania y Bielorrusia.",
      ContentP11:"En China, el método del calendario lunar para predecir el género de un feto se ha generalizado. Este método se basa en una tabla antigua compilada hace más de 1000 años. La tabla se calcula para la edad de la madre de 18 a 45 años. En él, para cada edad y mes en que se produjo la concepción, se indica el género del feto. La edad del padre no se usa para el cálculo.",
      ContentP12:"Esta tabla es fácil de encontrar en Internet. Sin embargo, debe tenerse en cuenta que para el cálculo correcto, debe especificar la edad y el mes de la concepción de acuerdo con el calendario lunar chino. La edad y la fecha de concepción en el calendario lunar y el europeo no coinciden. Esto se debe al hecho de que, según el calendario lunar, la edad en el momento del nacimiento ya es de 1 año, y no se agrega el día del nacimiento, sino en la fiesta nacional de la primavera o el Año Nuevo chino.",
      ContentP13:"BabyCalc traducirá automáticamente sus fechas al calendario lunar y realizará el cálculo correcto.",
      ContentP14:"Este método es utilizado por muchas familias chinas que quieren un hijo de cierto género.",
      ContentP15:"El método japonés para predecir el género del niño es similar al chino, pero también tiene en cuenta la fecha de nacimiento del padre. Incluye 2 tablas. En la primera tabla para cada pareja, \"mes de nacimiento del padre - mes de nacimiento de la madre\" contiene un número. En la segunda tabla, para cada número de la primera tabla y el mes calendario, se indica la probabilidad de concebir un niño o niña. Por lo tanto, el método japonés le permite planificar el género del feto para cualquier período de tiempo.",
      ContentP16:"Encontrar tablas de concepción japonesas en Internet es fácil. Para usarlos, no es necesario traducir las fechas al calendario lunar.",
      ContentP17:"Las encuestas muestran que la precisión del método japonés es del 70-80%.",
      ContentL1:"renovación de sangre,",
      ContentL2:"calendario lunar chino,",
      ContentL3:"tabla tradicional japonesa.",
      ContentH3_1: "¿Cómo funciona la predicción de género?",
      ContentH3_2: "¿Por qué las previsiones para diferentes métodos no coinciden?",
      ContentH3_3: "¿Qué métodos de cálculo usa este sitio?",
      ContentH4_1: "Método de renovación de sangre",
      ContentH4_2: "Calendario lunar chino",
      ContentH4_3: "Tabla japonesa",

    })
  ]
})
